
zigbee2mqtt:
 persistence:
   data:
     enabled: true
     accessMode: ReadWriteOnce
     size: 5Gi
   usb:
     enabled: true
     hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2251312-if00/
     type: hostPath
