
zigbee2mqtt:
  config:
    advanced:
      log_level: debug
    serial:
      port: /dev/ttyACM0
      adapter: deconz
  securityContext:
    privileged: true
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    usb:
      enabled: true
      hostPath: /dev/ttyACM0
      type: hostPath
