
zigbee2mqtt:
  frontend: true
  config:
    advanced:
      log_level: trace
    serial:
      adapter: deconz
      port: /dev/ttyACM0
      path: /dev/ttyACM0
      baudrate: 38400
    mqtt:
      server: mqtt://mosquito-mosquito.mosquito.svc:1883
  securityContext:
    privileged: true
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    usb:
      enabled: true
      hostPath: /dev/ttyACM0
      type: hostPath
