apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:nilsotto/argocd-apps.git'
    path: manifests/homeassistant
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  
