apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: home-assistant
    helm:
      parameters:
      - name: ingress.main.enabled
        value: "true"
      - name: ingress.main.host
        value: "hass.nojo.no"
      - name: persistence.config.enabled
        value: "true"
          #      - name: 
          #        value: 
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 12.0.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
