apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: home-assistant
    helm:
      parameters:
      - name: ingress.main.enabled
        value: true
          #      - name: 
          #        value: 
    repoURL: https://k8s-at-home.com/charts/
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
