apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquito
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:nilsotto/argocd-apps.git'
    path: manifest/mosquito
    targetRevision: HEAD
    helm:
      releaseName: mosquito
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mosquito
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  
