apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ser2sock
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:nilsotto/argocd-apps.git'
    path: manifests/ser2sock
    targetRevision: HEAD
    helm:
      releaseName: ser2sock
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: zigbee2mqtt
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  
