apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: zigbee2mqtt
spec:
  project: default
  source:
    repoURL: 'git@github.com:nilsotto/argocd-apps.git'
    path: manifests/zigbee2mqtt
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  
